source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'git-issue'
gem 'neovim'
gem 'pry-byebug'
gem 'slim_lint'
gem 'sqlint'
gem 'solargraph'
gem 'specific_install'
